export const SYSTEM_VIRUS_SCAN = '/api/soarFile/SystemVirusScan';
export const VIRUS_TOTAL_SCAN = '/api/soarFile/VirusTotalScan';
export const GET_VIRUS_TOTAL_REPORT = '/api/soarFile/GetVirusTotalReport';
export const CREATE_VIRUS_TOTAL_REPORT = '/api/soarFile/CreateVirusTotalReport';
export const VIRUS_TOTAL_SCAN_BY_ID = '/api/soarFile/VirusTotalScanById';
export const GET_SHA256 = '/api/soarFile/GetSha256';
export const GET_FILE_ALL = '/api/SoarFile/GetAll';
export const GET_FILE_INCIDENT = '/api/SoarFile/GetFileIncident?incidentId=';
export const FILL_UP_REPORT = '/api/SoarFile/FillUpVirusTotalReportById';